export const MENU = {
  APPETIZER: "애피타이저",
  SOUP: "양송이수프",
  TAPAS: "타파스",
  SALAD: "시저샐러드",
  MAIN: "메인",
  STAKE: "티본스테이크",
  BARBECUE: "바비큐립",
  SEAFOOD_PASTA: "해산물파스타",
  CHRISTMAS_PASTA: "크리스마스파스타",
  DESERT: "디저트",
  CAKE: "초코케이크",
  ICE_CREAM: "아이스크림",
  BEVERAGES: "음료",
  ZERO_COKE: "제로콜라",
  WINE: "레드와인",
  CHAMPAGNE: "샴페인",
};
