export const OUTPUT = {
  INTRO: "안녕하세요! 우테코 식당 12월 이벤트 플래너입니다.",
  PREVIEW: "12월 26일에 우테코 식당에서 받을 이벤트 혜택 미리 보기!",
  ORDER: "<주문 메뉴>",
  PRICE_BEFORE_DISCOUNT: "<할인 전 총주문 금액>",
  GIVEAWAYS: "<증정 메뉴>",
  DISCOUNT: "<혜택 내역>",
  TOTLA_DISCOUNT: "<총혜택 금액>",
  FINAL_PRICE: "<할인 후 예상 결제 금액>",
  BADGE: "<12월 이벤트 배지>",
  NOTHING: "없음",
  D_DAY_DISCOUNT: "크리스마스 디데이 할인",
  WEEKDAY_DISCOUNT: "평일 할인",
  SPECIAL_DISCOUNT: "특별 할인",
  GIVEAWAYS_EVENT: "증정 이벤트",
  WEEKEND_DISCOUNT: "주말 할인",
};
